sudo: required
services:
  - docker

before_install:
  - docker build -t mfarix/fe-react:latest -f Dockerfile-dev .

script:
  - docker run mfarix/fe-react:latest npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "fe-react"
  env: "FeReact-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-512200996832"
  bucket_path: "fe-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
