version: '3'
services:
  webapp:
    image: mfarix/fe-react:latest
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
  tests:
    image: mfarix/fe-react:latest
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]
