version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:18.06.1-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          apk update
          apk add --no-cache py-pip
          pip install docker-compose==1.21.2 awscli==1.16.81
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/app.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/app.tar | true
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=app -t ${ECR_ENDPOINT}/${ECR_REPOSITORY} .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/app.tar app
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/app.tar
      - run:
          name: Run tests
          command: |
            docker-compose -f ./docker-compose.test.yml up
      - deploy:
          name: Push application Docker image
          command: |
            REPOSITORY_URI=${ECR_ENDPOINT}/${ECR_REPOSITORY}
            IMAGE_TAG=$(echo $CIRCLE_SHA1 | cut -c 1-7)
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
              docker tag "${REPOSITORY_URI}:latest" "${REPOSITORY_URI}:${IMAGE_TAG}"
              docker push "${REPOSITORY_URI}:${IMAGE_TAG}"
              docker push "${REPOSITORY_URI}:latest"
            fi
